apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: corse
          value: "Devops"
        - name: tarainer
          value: "sivakumar reddy"
        - name: duration
          value: "120hrs"